---
name: SimpleSpawns
version: 4.0-BETA
main: jonygamesyt9\simplespawns\SimpleSpawns
api: 4.0.0
author: JonyGamesYT9 (iJonyMx)
permissions:
  simplespawns.command.setlobby:
    description: "Get permission to place the lobby wherever you want."
    default: op
  simplespawns.command.lobby:
    description: "Get permission to teleport to the lobby."
    default: op
...