---
name: SimpleSpawns
main: JonyGamesYT9\SimpleSpawns\SimpleSpawns
api: [3.0.0]
version: 2.0.0
author: JonyGamesYT9 
description: Spawns system for PocketMine-MP
website: https://github.com/JonyGamesYT9

permissions:
 simplespawns.setlobby:
   description: "Get permission to place the lobby wherever you want."
   default: op 
...
