---
name: SimpleSpawns
main: JonyGamesYT9\SimpleSpawns\SimpleSpawns
api: [3.0.0]
version: 1.0.0
author: JonyGamesYT9 
description: Spawns system for PocketMine-MP
website: https://github.com/JonyGamesYT9
load: STARTUP

permissions:
 spawns.command.setlobby:
   description: "Get full access to the help command."
   default: op 
...
